org: torresramos # Uso de la organización
service: actualizar-productos

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::367311722984:role/LabRole
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeStream"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:ListStreams"
      Resource: "arn:aws:dynamodb:us-east-1:367311722984:table/${self:provider.stage}_cursos/stream/*" # ARN del stream

functions:
  actualizarProductos:
    handler: index.handler
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:367311722984:table/dev_cursos/stream/2025-07-04T23:50:48.611 # Reemplaza con el ARN correcto del Stream
          batchSize: 5
          startingPosition: LATEST
    environment:
      ES_HOST: '34.206.17.81'  # IP de tu Elasticsearch
      ES_PORT: 9200
      ES_INDEX: 'productos'
